### ISSUE TITLE
css-loader - Can't resolve 'fs' when bundle with webpack

### ISSUE THREAD

**Issue by abhijithvijayan** [shaminmeerankutty/webpack-sass-bootstrap-boilerplate#19]
![](http://bit.ly/2EqyiIr)
webpack throwing errors 
[Fix](https://github.com/webpack-contrib/css-loader/issues/447#issuecomment-285600014) for this error 

Adding 

`  node: {
    fs: 'empty'
  },`
in `webpack-config` file solves the issue

**Comment by abhijithvijayan** [comment]
?

**Comment by shaminmeerankutty** [comment]
@abhijithvijayan Is this error in windows?

**Comment by abhijithvijayan** [comment]
> 
> 
> @abhijithvijayan Is this error happening in windows?

Yes

**Comment by abhijithvijayan** [comment]
> 
> 
> @abhijithvijayan I have pushed the fixes. Can you please try it whether it is working fine.

I've already done the fix on the project I was on. It works smoothly. Thanks.

**Comment by shaminmeerankutty** [comment]
> @shaminmeerankutty
> I've already done the fix on the project I was on. It works smoothly.
> 
> The only error I see everytime is `[WDS] Disconnected!`, other than that, everything works!!
> 
> Thanks.

Is that error shown when the process is stopped?

**Comment by abhijithvijayan** [comment]
> > @shaminmeerankutty
> > The only error I see everytime is `[WDS] Disconnected!`, other than that, everything works!!
> 
> Is that error shown when the process is stopped?

No, It pops up every time webpack compiles. I tried changing the port to 3000 but still no luck. I think it is webpack bug. See this [issue](https://github.com/webpack/webpack-dev-server/issues/1419)
