### ISSUE TITLE
Create a documentation page

### ISSUE THREAD

**Issue by shaminmeerankutty** [shaminmeerankutty/webpack-sass-bootstrap-boilerplate#4]
Need help with setting up a documentation page for this repo. Documentation page should be added in the `docs` directory at the project root, so that it can be served by github pages.

**Comment by shaminmeerankutty** [comment]
@rajatjain-21 Just created a simple issue to help someone who actually needs to get a good contribution to open source rather than adding their names to contibuting.md. By creating a documentation page with `html` & `css` they will be getting confidence with these technologies.

**Comment by silvia-odwyer** [comment]
I think mkdocs would be the best way to go about this, and the documentation can be served on readthedocs.io if you would like, or else gh-pages also. Would you like me to get started with this?

**Comment by shaminmeerankutty** [comment]
@silvia-odwyer You can go for `mkdocs` I am okay with that. I am planning to host the documentation in `gh-pages`.

**Comment by silvia-odwyer** [comment]
That's perfect. I'll have the PR submitted to you in the next few hours or so.
