### ISSUE TITLE
Autoprefixer / postcss-loader

### ISSUE THREAD

**Issue by mrsamse** [shaminmeerankutty/webpack-sass-bootstrap-boilerplate#8]
Hi there

This is just the boilerplate I was looking for. Thank you!

Quick question:
Doesn't bootstrap need postcss-loader for prefixing? The documentation says so: https://getbootstrap.com/docs/4.0/getting-started/webpack/

Greetings

**Comment by shaminmeerankutty** [comment]
@mrsamse When I wrote the boilerplate bootstrap was at v4 alpha and then `postcss-loader` was not a required one. May be now they start using `Autoprefixer`. If you want you can raise a new PR adding css-loader or else I will update the changes.
